spring:
  application:
    name: dubbo-provider-demo
  profiles:
    include: nacos

dubbo:
  protocols:
    dubbo:
      name: dubbo
      port: 20880

  scan:
    base-packages: com.sky.dubbo.nacos.demo.provider

demo:
  service:
    version: 1.0.0
    name: demoService
