dubbo:
  registry:
    id: my-nacos
    address: nacos://69.28.48.244:8848
    simplified: true

  metadata-report:
    address: nacos://69.28.48.244:8848

  config-center:
    address: nacos://69.28.48.244:8848
    group: dubbo-provider-demo
    namespace:
    config-file: dubbo.properties
    include-spring-env: true