dubbo:
  registry:
    id: my-zookeeper
    address: zookeeper://69.28.48.244:2181
    simplified: true

  metadata-report:
    address: zookeeper://69.28.48.244:2181

  config-center:
    address: zookeeper://69.28.48.244:2181
