
dubbo:
  application:
    id: dubbo-provider-demo
    name: dubbo-provider-demo

  protocols:
    dubbo:
      name: dubbo
      port: 20880

  scan:
    base-packages: com.sky.dubbo.nacos.demo.provider

demo:
  service:
    version: 1.0.0
    name: demoService

spring:
  profiles:
    include: nacos
