dubbo:
  registry:
    address: zookeeper://69.28.48.244:2181

  application:
    name: dubbo-consumer-demo

nacos:
  config:
    server-addr: 69.28.48.244:8848

demo:
  service:
    version: 1.0.0

spring:
  profiles:
    include: nacos
