dubbo:
  registry:
    address: zookeeper://69.28.48.244:2181

  application:
    name: dubbo-consumer-demo

demo:
  service:
    version: 1.0.0
    name: demoService

spring:
  profiles:
    include: nacos
